services:
  - type: web
    name: hr-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: GROUP_LINK_RU
        sync: false
      - key: GROUP_LINK_EN
        sync: false
      - key: GROUP_LINK_HE
        sync: false